spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_pos
    username: mini_pos
    password: mini_pos2233

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
